# Generated by Django 3.1.7 on 2021-03-08 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210307_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lis_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
