# Generated by Django 3.1.7 on 2021-03-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210308_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='listing',
            name='lis_description',
            field=models.TextField(max_length=500, verbose_name='description'),
        ),
    ]
